FROM golang:1.14

WORKDIR /work

RUN apt-get update
RUN apt install -y protobuf-compiler

RUN GO111MODULE=on \
        go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.26.0 \
        google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0 \
