FROM golang:1.18

WORKDIR /work

RUN apt-get update
RUN apt install -y protobuf-compiler python3 python3-pip
RUN pip install grpcio-tools

RUN GO111MODULE=on
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
