# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calendar_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63\x61lendar_service.proto\x12\x08\x63\x61lendar\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\x05\x45vent\x12\x0f\n\x07\x65ventId\x18\x01 \x01(\t\"\x14\n\x04Week\x12\x0c\n\x04week\x18\x01 \x01(\x05\"\x18\n\x06\x45vents\x12\x0e\n\x06\x65vents\x18\x01 \x03(\t2\xb1\x01\n\x0f\x43\x61lendarService\x12\x34\n\tsendEvent\x12\x0f.calendar.Event\x1a\x16.google.protobuf.Empty\x12\x39\n\x0crecieveEvent\x12\x16.google.protobuf.Empty\x1a\x0f.calendar.Event0\x01\x12-\n\tgetEvents\x12\x0e.calendar.Week\x1a\x10.calendar.EventsB\x07Z\x05/;apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calendar_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005/;api'
  _EVENT._serialized_start=65
  _EVENT._serialized_end=89
  _WEEK._serialized_start=91
  _WEEK._serialized_end=111
  _EVENTS._serialized_start=113
  _EVENTS._serialized_end=137
  _CALENDARSERVICE._serialized_start=140
  _CALENDARSERVICE._serialized_end=317
# @@protoc_insertion_point(module_scope)
