# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anotification_service.proto\x12\x0cnotification\x1a\x1bgoogle/protobuf/empty.proto\";\n\x0cNotification\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t2b\n\x13NotificationService\x12K\n\x13RecieveNotification\x12\x16.google.protobuf.Empty\x1a\x1a.notification.Notification0\x01\x42\x07Z\x05/;apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005/;api'
  _NOTIFICATION._serialized_start=73
  _NOTIFICATION._serialized_end=132
  _NOTIFICATIONSERVICE._serialized_start=134
  _NOTIFICATIONSERVICE._serialized_end=232
# @@protoc_insertion_point(module_scope)
