# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import user_service_pb2 as user__service__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.signIn = channel.unary_unary(
                '/user.User/signIn',
                request_serializer=user__service__pb2.SignIn.SerializeToString,
                response_deserializer=user__service__pb2.Response.FromString,
                )
        self.signUp = channel.unary_unary(
                '/user.User/signUp',
                request_serializer=user__service__pb2.SignUp.SerializeToString,
                response_deserializer=user__service__pb2.Response.FromString,
                )
        self.editUser = channel.unary_unary(
                '/user.User/editUser',
                request_serializer=user__service__pb2.UserData.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def signIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def signUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def editUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'signIn': grpc.unary_unary_rpc_method_handler(
                    servicer.signIn,
                    request_deserializer=user__service__pb2.SignIn.FromString,
                    response_serializer=user__service__pb2.Response.SerializeToString,
            ),
            'signUp': grpc.unary_unary_rpc_method_handler(
                    servicer.signUp,
                    request_deserializer=user__service__pb2.SignUp.FromString,
                    response_serializer=user__service__pb2.Response.SerializeToString,
            ),
            'editUser': grpc.unary_unary_rpc_method_handler(
                    servicer.editUser,
                    request_deserializer=user__service__pb2.UserData.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def signIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.User/signIn',
            user__service__pb2.SignIn.SerializeToString,
            user__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def signUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.User/signUp',
            user__service__pb2.SignUp.SerializeToString,
            user__service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def editUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.User/editUser',
            user__service__pb2.UserData.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
