version: "3.9"

services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "8081:8081"
    # links:
    #   - mongo
    network_mode: "host"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    network_mode: "host"
