// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user_service.proto
#ifndef GRPC_user_5fservice_2eproto__INCLUDED
#define GRPC_user_5fservice_2eproto__INCLUDED

#include "user_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace user {

class User final {
 public:
  static constexpr char const* service_full_name() {
    return "user.User";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status signIn(::grpc::ClientContext* context, const ::user::SignIn& request, ::user::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>> AsyncsignIn(::grpc::ClientContext* context, const ::user::SignIn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>>(AsyncsignInRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>> PrepareAsyncsignIn(::grpc::ClientContext* context, const ::user::SignIn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>>(PrepareAsyncsignInRaw(context, request, cq));
    }
    virtual ::grpc::Status signUp(::grpc::ClientContext* context, const ::user::SignUp& request, ::user::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>> AsyncsignUp(::grpc::ClientContext* context, const ::user::SignUp& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>>(AsyncsignUpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>> PrepareAsyncsignUp(::grpc::ClientContext* context, const ::user::SignUp& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>>(PrepareAsyncsignUpRaw(context, request, cq));
    }
    virtual ::grpc::Status editUser(::grpc::ClientContext* context, const ::user::UserData& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsynceditUser(::grpc::ClientContext* context, const ::user::UserData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsynceditUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsynceditUser(::grpc::ClientContext* context, const ::user::UserData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsynceditUserRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void signIn(::grpc::ClientContext* context, const ::user::SignIn* request, ::user::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void signIn(::grpc::ClientContext* context, const ::user::SignIn* request, ::user::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void signUp(::grpc::ClientContext* context, const ::user::SignUp* request, ::user::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void signUp(::grpc::ClientContext* context, const ::user::SignUp* request, ::user::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void editUser(::grpc::ClientContext* context, const ::user::UserData* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void editUser(::grpc::ClientContext* context, const ::user::UserData* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>* AsyncsignInRaw(::grpc::ClientContext* context, const ::user::SignIn& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>* PrepareAsyncsignInRaw(::grpc::ClientContext* context, const ::user::SignIn& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>* AsyncsignUpRaw(::grpc::ClientContext* context, const ::user::SignUp& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::Response>* PrepareAsyncsignUpRaw(::grpc::ClientContext* context, const ::user::SignUp& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsynceditUserRaw(::grpc::ClientContext* context, const ::user::UserData& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsynceditUserRaw(::grpc::ClientContext* context, const ::user::UserData& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status signIn(::grpc::ClientContext* context, const ::user::SignIn& request, ::user::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::Response>> AsyncsignIn(::grpc::ClientContext* context, const ::user::SignIn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::Response>>(AsyncsignInRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::Response>> PrepareAsyncsignIn(::grpc::ClientContext* context, const ::user::SignIn& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::Response>>(PrepareAsyncsignInRaw(context, request, cq));
    }
    ::grpc::Status signUp(::grpc::ClientContext* context, const ::user::SignUp& request, ::user::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::Response>> AsyncsignUp(::grpc::ClientContext* context, const ::user::SignUp& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::Response>>(AsyncsignUpRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::Response>> PrepareAsyncsignUp(::grpc::ClientContext* context, const ::user::SignUp& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::Response>>(PrepareAsyncsignUpRaw(context, request, cq));
    }
    ::grpc::Status editUser(::grpc::ClientContext* context, const ::user::UserData& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsynceditUser(::grpc::ClientContext* context, const ::user::UserData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsynceditUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsynceditUser(::grpc::ClientContext* context, const ::user::UserData& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsynceditUserRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void signIn(::grpc::ClientContext* context, const ::user::SignIn* request, ::user::Response* response, std::function<void(::grpc::Status)>) override;
      void signIn(::grpc::ClientContext* context, const ::user::SignIn* request, ::user::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void signUp(::grpc::ClientContext* context, const ::user::SignUp* request, ::user::Response* response, std::function<void(::grpc::Status)>) override;
      void signUp(::grpc::ClientContext* context, const ::user::SignUp* request, ::user::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void editUser(::grpc::ClientContext* context, const ::user::UserData* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void editUser(::grpc::ClientContext* context, const ::user::UserData* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::user::Response>* AsyncsignInRaw(::grpc::ClientContext* context, const ::user::SignIn& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::Response>* PrepareAsyncsignInRaw(::grpc::ClientContext* context, const ::user::SignIn& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::Response>* AsyncsignUpRaw(::grpc::ClientContext* context, const ::user::SignUp& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::Response>* PrepareAsyncsignUpRaw(::grpc::ClientContext* context, const ::user::SignUp& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsynceditUserRaw(::grpc::ClientContext* context, const ::user::UserData& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsynceditUserRaw(::grpc::ClientContext* context, const ::user::UserData& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_signIn_;
    const ::grpc::internal::RpcMethod rpcmethod_signUp_;
    const ::grpc::internal::RpcMethod rpcmethod_editUser_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status signIn(::grpc::ServerContext* context, const ::user::SignIn* request, ::user::Response* response);
    virtual ::grpc::Status signUp(::grpc::ServerContext* context, const ::user::SignUp* request, ::user::Response* response);
    virtual ::grpc::Status editUser(::grpc::ServerContext* context, const ::user::UserData* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_signIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_signIn() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_signIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signIn(::grpc::ServerContext* /*context*/, const ::user::SignIn* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsignIn(::grpc::ServerContext* context, ::user::SignIn* request, ::grpc::ServerAsyncResponseWriter< ::user::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_signUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_signUp() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_signUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signUp(::grpc::ServerContext* /*context*/, const ::user::SignUp* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsignUp(::grpc::ServerContext* context, ::user::SignUp* request, ::grpc::ServerAsyncResponseWriter< ::user::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_editUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_editUser() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_editUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status editUser(::grpc::ServerContext* /*context*/, const ::user::UserData* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequesteditUser(::grpc::ServerContext* context, ::user::UserData* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_signIn<WithAsyncMethod_signUp<WithAsyncMethod_editUser<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_signIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_signIn() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::user::SignIn, ::user::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::SignIn* request, ::user::Response* response) { return this->signIn(context, request, response); }));}
    void SetMessageAllocatorFor_signIn(
        ::grpc::MessageAllocator< ::user::SignIn, ::user::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::SignIn, ::user::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_signIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signIn(::grpc::ServerContext* /*context*/, const ::user::SignIn* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* signIn(
      ::grpc::CallbackServerContext* /*context*/, const ::user::SignIn* /*request*/, ::user::Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_signUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_signUp() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::user::SignUp, ::user::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::SignUp* request, ::user::Response* response) { return this->signUp(context, request, response); }));}
    void SetMessageAllocatorFor_signUp(
        ::grpc::MessageAllocator< ::user::SignUp, ::user::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::SignUp, ::user::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_signUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signUp(::grpc::ServerContext* /*context*/, const ::user::SignUp* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* signUp(
      ::grpc::CallbackServerContext* /*context*/, const ::user::SignUp* /*request*/, ::user::Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_editUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_editUser() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::user::UserData, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::UserData* request, ::google::protobuf::Empty* response) { return this->editUser(context, request, response); }));}
    void SetMessageAllocatorFor_editUser(
        ::grpc::MessageAllocator< ::user::UserData, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::UserData, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_editUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status editUser(::grpc::ServerContext* /*context*/, const ::user::UserData* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* editUser(
      ::grpc::CallbackServerContext* /*context*/, const ::user::UserData* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_signIn<WithCallbackMethod_signUp<WithCallbackMethod_editUser<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_signIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_signIn() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_signIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signIn(::grpc::ServerContext* /*context*/, const ::user::SignIn* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_signUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_signUp() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_signUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signUp(::grpc::ServerContext* /*context*/, const ::user::SignUp* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_editUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_editUser() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_editUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status editUser(::grpc::ServerContext* /*context*/, const ::user::UserData* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_signIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_signIn() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_signIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signIn(::grpc::ServerContext* /*context*/, const ::user::SignIn* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsignIn(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_signUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_signUp() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_signUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signUp(::grpc::ServerContext* /*context*/, const ::user::SignUp* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsignUp(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_editUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_editUser() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_editUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status editUser(::grpc::ServerContext* /*context*/, const ::user::UserData* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequesteditUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_signIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_signIn() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->signIn(context, request, response); }));
    }
    ~WithRawCallbackMethod_signIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signIn(::grpc::ServerContext* /*context*/, const ::user::SignIn* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* signIn(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_signUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_signUp() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->signUp(context, request, response); }));
    }
    ~WithRawCallbackMethod_signUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status signUp(::grpc::ServerContext* /*context*/, const ::user::SignUp* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* signUp(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_editUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_editUser() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->editUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_editUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status editUser(::grpc::ServerContext* /*context*/, const ::user::UserData* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* editUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_signIn : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_signIn() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::SignIn, ::user::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::SignIn, ::user::Response>* streamer) {
                       return this->StreamedsignIn(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_signIn() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status signIn(::grpc::ServerContext* /*context*/, const ::user::SignIn* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsignIn(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::SignIn,::user::Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_signUp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_signUp() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::SignUp, ::user::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::SignUp, ::user::Response>* streamer) {
                       return this->StreamedsignUp(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_signUp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status signUp(::grpc::ServerContext* /*context*/, const ::user::SignUp* /*request*/, ::user::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsignUp(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::SignUp,::user::Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_editUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_editUser() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::UserData, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::UserData, ::google::protobuf::Empty>* streamer) {
                       return this->StreamededitUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_editUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status editUser(::grpc::ServerContext* /*context*/, const ::user::UserData* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamededitUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::UserData,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_signIn<WithStreamedUnaryMethod_signUp<WithStreamedUnaryMethod_editUser<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_signIn<WithStreamedUnaryMethod_signUp<WithStreamedUnaryMethod_editUser<Service > > > StreamedService;
};

}  // namespace user


#endif  // GRPC_user_5fservice_2eproto__INCLUDED
