# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_service.proto\x12\x04\x63hat\x1a\x1bgoogle/protobuf/empty.proto\"y\n\x08\x43hatInfo\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\nsecondLine\x18\x03 \x01(\t\x12\x13\n\x0blastMessage\x18\x04 \x01(\t\x12\x15\n\runreadedCount\x18\x05 \x01(\x03\x12\r\n\x05\x63over\x18\x06 \x01(\t\"&\n\x05\x43hats\x12\x1d\n\x05\x63hats\x18\x01 \x03(\x0b\x32\x0e.chat.ChatInfo\"E\n\x0bMessageChan\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\"\n\tdirection\x18\x02 \x01(\x0e\x32\x0f.chat.Direction\"G\n\x07Message\x12&\n\x0bmessageType\x18\x01 \x01(\x0e\x32\x11.chat.MessageType\x12\x14\n\x0cmessage_json\x18\x02 \x01(\t\"+\n\x08Messages\x12\x1f\n\x08messages\x18\x01 \x03(\x0b\x32\r.chat.Message\"\x19\n\x06UserID\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\x1f\n\tMessageID\x12\x12\n\nmessage_id\x18\x01 \x01(\t\"\x18\n\x08\x43hatData\x12\x0c\n\x04json\x18\x01 \x01(\t\"C\n\x10\x45xchangedMessage\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x1e\n\x07message\x18\x02 \x01(\x0b\x32\r.chat.Message\"2\n\x0bReadMessage\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t*&\n\tDirection\x12\x0b\n\x07\x46orward\x10\x00\x12\x0c\n\x08\x42\x61\x63kward\x10\x01*\x19\n\x0bMessageType\x12\n\n\x06Normal\x10\x00\x32\x89\x03\n\x04\x43hat\x12%\n\x08getChats\x12\x0c.chat.UserID\x1a\x0b.chat.Chats\x12\x30\n\x0bgetMessages\x12\x11.chat.MessageChan\x1a\x0e.chat.Messages\x12\x38\n\x0breadMessage\x12\x11.chat.ReadMessage\x1a\x16.google.protobuf.Empty\x12\x32\n\x08\x65\x64itChat\x12\x0e.chat.ChatData\x1a\x16.google.protobuf.Empty\x12\x37\n\x0b\x63hatChanged\x12\x16.google.protobuf.Empty\x1a\x0e.chat.ChatData0\x01\x12=\n\x0bsendMessage\x12\x16.chat.ExchangedMessage\x1a\x16.google.protobuf.Empty\x12\x42\n\x0erecieveMessage\x12\x16.google.protobuf.Empty\x1a\x16.chat.ExchangedMessage0\x01\x42\x07Z\x05/;apib\x06proto3')

_DIRECTION = DESCRIPTOR.enum_types_by_name['Direction']
Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
_MESSAGETYPE = DESCRIPTOR.enum_types_by_name['MessageType']
MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
Forward = 0
Backward = 1
Normal = 0


_CHATINFO = DESCRIPTOR.message_types_by_name['ChatInfo']
_CHATS = DESCRIPTOR.message_types_by_name['Chats']
_MESSAGECHAN = DESCRIPTOR.message_types_by_name['MessageChan']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_MESSAGES = DESCRIPTOR.message_types_by_name['Messages']
_USERID = DESCRIPTOR.message_types_by_name['UserID']
_MESSAGEID = DESCRIPTOR.message_types_by_name['MessageID']
_CHATDATA = DESCRIPTOR.message_types_by_name['ChatData']
_EXCHANGEDMESSAGE = DESCRIPTOR.message_types_by_name['ExchangedMessage']
_READMESSAGE = DESCRIPTOR.message_types_by_name['ReadMessage']
ChatInfo = _reflection.GeneratedProtocolMessageType('ChatInfo', (_message.Message,), {
  'DESCRIPTOR' : _CHATINFO,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatInfo)
  })
_sym_db.RegisterMessage(ChatInfo)

Chats = _reflection.GeneratedProtocolMessageType('Chats', (_message.Message,), {
  'DESCRIPTOR' : _CHATS,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.Chats)
  })
_sym_db.RegisterMessage(Chats)

MessageChan = _reflection.GeneratedProtocolMessageType('MessageChan', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGECHAN,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.MessageChan)
  })
_sym_db.RegisterMessage(MessageChan)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.Message)
  })
_sym_db.RegisterMessage(Message)

Messages = _reflection.GeneratedProtocolMessageType('Messages', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGES,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.Messages)
  })
_sym_db.RegisterMessage(Messages)

UserID = _reflection.GeneratedProtocolMessageType('UserID', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.UserID)
  })
_sym_db.RegisterMessage(UserID)

MessageID = _reflection.GeneratedProtocolMessageType('MessageID', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEID,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.MessageID)
  })
_sym_db.RegisterMessage(MessageID)

ChatData = _reflection.GeneratedProtocolMessageType('ChatData', (_message.Message,), {
  'DESCRIPTOR' : _CHATDATA,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.ChatData)
  })
_sym_db.RegisterMessage(ChatData)

ExchangedMessage = _reflection.GeneratedProtocolMessageType('ExchangedMessage', (_message.Message,), {
  'DESCRIPTOR' : _EXCHANGEDMESSAGE,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.ExchangedMessage)
  })
_sym_db.RegisterMessage(ExchangedMessage)

ReadMessage = _reflection.GeneratedProtocolMessageType('ReadMessage', (_message.Message,), {
  'DESCRIPTOR' : _READMESSAGE,
  '__module__' : 'chat_service_pb2'
  # @@protoc_insertion_point(class_scope:chat.ReadMessage)
  })
_sym_db.RegisterMessage(ReadMessage)

_CHAT = DESCRIPTOR.services_by_name['Chat']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005/;api'
  _DIRECTION._serialized_start=616
  _DIRECTION._serialized_end=654
  _MESSAGETYPE._serialized_start=656
  _MESSAGETYPE._serialized_end=681
  _CHATINFO._serialized_start=57
  _CHATINFO._serialized_end=178
  _CHATS._serialized_start=180
  _CHATS._serialized_end=218
  _MESSAGECHAN._serialized_start=220
  _MESSAGECHAN._serialized_end=289
  _MESSAGE._serialized_start=291
  _MESSAGE._serialized_end=362
  _MESSAGES._serialized_start=364
  _MESSAGES._serialized_end=407
  _USERID._serialized_start=409
  _USERID._serialized_end=434
  _MESSAGEID._serialized_start=436
  _MESSAGEID._serialized_end=467
  _CHATDATA._serialized_start=469
  _CHATDATA._serialized_end=493
  _EXCHANGEDMESSAGE._serialized_start=495
  _EXCHANGEDMESSAGE._serialized_end=562
  _READMESSAGE._serialized_start=564
  _READMESSAGE._serialized_end=614
  _CHAT._serialized_start=684
  _CHAT._serialized_end=1077
# @@protoc_insertion_point(module_scope)
