# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\")\n\x06SignIn\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"s\n\x06SignUp\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08nickName\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x19\n\x11\x63onfirmedPassword\x18\x05 \x01(\t\x12\r\n\x05photo\x18\x06 \x01(\t\"\x87\x01\n\x08Response\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08nickName\x18\x03 \x01(\t\x12\r\n\x05photo\x18\x04 \x01(\t\x12$\n\x06status\x18\x05 \x01(\x0e\x32\x14.user.ResponseStatus\x12\x15\n\rstatusMessage\x18\x06 \x01(\t\"Y\n\x08UserInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08nickName\x18\x03 \x01(\t\x12\r\n\x05photo\x18\x04 \x01(\t\x12\r\n\x05\x63hats\x18\x05 \x03(\t\"\x18\n\x08UserData\x12\x0c\n\x04json\x18\x01 \x01(\t*#\n\x0eResponseStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45rror\x10\x01\x32\x8a\x01\n\x04User\x12&\n\x06signIn\x12\x0c.user.SignIn\x1a\x0e.user.Response\x12&\n\x06signUp\x12\x0c.user.SignUp\x1a\x0e.user.Response\x12\x32\n\x08\x65\x64itUser\x12\x0e.user.UserData\x1a\x16.google.protobuf.EmptyB\x07Z\x05/;apib\x06proto3')

_RESPONSESTATUS = DESCRIPTOR.enum_types_by_name['ResponseStatus']
ResponseStatus = enum_type_wrapper.EnumTypeWrapper(_RESPONSESTATUS)
OK = 0
Error = 1


_SIGNIN = DESCRIPTOR.message_types_by_name['SignIn']
_SIGNUP = DESCRIPTOR.message_types_by_name['SignUp']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_USERINFO = DESCRIPTOR.message_types_by_name['UserInfo']
_USERDATA = DESCRIPTOR.message_types_by_name['UserData']
SignIn = _reflection.GeneratedProtocolMessageType('SignIn', (_message.Message,), {
  'DESCRIPTOR' : _SIGNIN,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:user.SignIn)
  })
_sym_db.RegisterMessage(SignIn)

SignUp = _reflection.GeneratedProtocolMessageType('SignUp', (_message.Message,), {
  'DESCRIPTOR' : _SIGNUP,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:user.SignUp)
  })
_sym_db.RegisterMessage(SignUp)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:user.Response)
  })
_sym_db.RegisterMessage(Response)

UserInfo = _reflection.GeneratedProtocolMessageType('UserInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERINFO,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:user.UserInfo)
  })
_sym_db.RegisterMessage(UserInfo)

UserData = _reflection.GeneratedProtocolMessageType('UserData', (_message.Message,), {
  'DESCRIPTOR' : _USERDATA,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:user.UserData)
  })
_sym_db.RegisterMessage(UserData)

_USER = DESCRIPTOR.services_by_name['User']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005/;api'
  _RESPONSESTATUS._serialized_start=472
  _RESPONSESTATUS._serialized_end=507
  _SIGNIN._serialized_start=57
  _SIGNIN._serialized_end=98
  _SIGNUP._serialized_start=100
  _SIGNUP._serialized_end=215
  _RESPONSE._serialized_start=218
  _RESPONSE._serialized_end=353
  _USERINFO._serialized_start=355
  _USERINFO._serialized_end=444
  _USERDATA._serialized_start=446
  _USERDATA._serialized_end=470
  _USER._serialized_start=510
  _USER._serialized_end=648
# @@protoc_insertion_point(module_scope)
